run:
  name: default
  description: text description of the run
  seed: 42
  sample_pct: 1 #of 100

sampling:
  tuning_validation_pct: 1 #of 100
  evaluation_pct: 1 #of 100

paths:
  baseline_root: output/08_baseline_results

data:
  parquet_dir: output/07_parquet
  split: test
  context_filter_tuning: null
  context_filter_evaluation: null
  context_filter_tuning: null
  context_filter_evaluation: null

evaluation:
  export_predictions: true

models:
  cv: true
  ctrv: false
  ctrv_arc: false
  hybrid: false
  kalman: false
  ctrv_ekf: false
  tirex_lstm: false
  chronos2_zero_shot: true
  tirex:
    model_name: NX-AI/TiRex
    device: cuda # null-> auto-detect, or specify "cpu" or "cuda"
    backend: cuda # torch as fallback for windows, use cuda on linux, recommended and faster
    compile_model: true
    scaler_path: output/05_normalized/scalers.pkl
  chronos2:
    model_name: amazon/chronos-2
    # device_map controls which device(s) the model is loaded onto.
    # Use "cuda" for the first GPU, "cuda:N" for a specific GPU by index, starting at 0,
    # "cpu" to force CPU, or "auto".
    #
    # max_memory limits how much GPU memory (in GB) is allocated per device (keyed by GPU index).
    device_map: cuda:1
    max_memory: {1: "11GB"}
    torch_dtype: float32
    context_length: 10
    prediction_length: 10
    scaler_path: output/05_normalized/scalers.pkl

tuning:
  n_trials_standard: 30
  n_trials_tirex: 1 # just testing if it runs
  n_trials_hybrid: 100
  n_trials_kalman: 100
  n_trials_ctrv_ekf: 100
  early_stopping_patience: 50
  early_stopping_min_delta: 0.0001

plotting:
  step_duration_s: 30
  models:
    constant_velocity: true
    ctrv: false
    ctrv_arc: false
    hybrid_cv_ctrv: false
    kalman: false
    ctrv_ekf: true
    tirex_lstm: false
    chronos2_zero_shot: true
