run:
  name: lstm_river_river_
  description: 100 prozent kein filter
  seed: 42
  sample_pct: 100 #of 100

sampling:
  tuning_validation_pct: 100 #of 100
  evaluation_pct: 100 #of 100

paths:
  baseline_root: output/08_baseline_results

data:
  parquet_dir: output/07_parquet
  split: test
  context_filter_tuning: river # null, not none
  context_filter_evaluation: river # null


evaluation:
  export_predictions: true

models:
  cv: false
  ctrv: false
  ctrv_arc: false
  hybrid: false
  kalman: false
  ctrv_ekf: false
  tirex_lstm: false
  minimal_lstm: true
  chronos2_zero_shot: false
  tirex:
    model_name: NX-AI/TiRex
    device: cuda # null-> auto-detect, or specify "cpu" or "cuda"
    backend: cuda # cuda # torch + GPU as fallback because of compatibility issues 
    compile_model: true
    batch_size: 256000 # tracks per forecast call; reduce if GPU OOM
    scaler_path: output/05_normalized/scalers.pkl
  chronos2:
    model_name: amazon/chronos-2
    # device_map controls which device(s) the model is loaded onto.
    # Use "cuda" for the first GPU, "cuda:N" for a specific GPU by index, starting at 0,
    # "cpu" to force CPU, or "auto".
    #
    device_map: cuda #{0: "cuda:0", 1: "cuda:1"} # use both gpus explicitly
    max_memory: {0: "8GB", 1: "11GB"}
    torch_dtype: float32
    context_length: 10
    prediction_length: 10
    scaler_path: output/05_normalized/scalers.pkl
  minimal_lstm_cfg:
    checkpoint_path: output/08_baseline_results/models/minimal_lstm.pt
    scaler_path: output/05_normalized/scalers.pkl
    device: cuda # cpu or cuda
    preload_to_gpu: true
    max_epochs: 60
    patience: 8
    min_delta: 0.0001

tuning:
  n_trials_standard: 30
  n_trials_hybrid: 100
  n_trials_kalman: 100
  n_trials_ctrv_ekf: 100
  n_trials_minimal_lstm: 30
  early_stopping_patience: 50
  early_stopping_min_delta: 0.0001
  minimal_lstm:
    hidden_size: [64, 128, 256]
    num_layers: [1, 2]
    dropout_min: 0.1
    dropout_max: 0.4
    learning_rate_min: 0.0001
    learning_rate_max: 0.01
    batch_size: [128, 256, 512]

plotting:
  step_duration_s: 30
  models:
    constant_velocity: false
    ctrv: false
    ctrv_arc: false
    hybrid_cv_ctrv: false
    kalman: false
    ctrv_ekf: false
    tirex_lstm: false
    chronos2_zero_shot: false
    minimal_lstm: true
